"""empty message

Revision ID: 4ab5c2bf3c16
Revises: 3201e9f63a5c
Create Date: 2020-07-10 09:23:58.499070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab5c2bf3c16'
down_revision = '3201e9f63a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Referral', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Referral', 'score')
    # ### end Alembic commands ###
